CREATE TABLE PhysicsGames (
    ID UNIQUEIDENTIFIER NOT NULL,
    CreatorID UNIQUEIDENTIFIER NOT NULL,
    JoinCode NVARCHAR(100) NOT NULL,
    GameStart DATETIME NOT NULL,
    NumPlayers INT NOT NULL,
    CurrentRound INT NOT NULL,
    GameEnd DATETIME NULL,
    WinningPlayerID UNIQUEIDENTIFIER NULL,
    WinningPlayerName NVARCHAR(1000) NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE PhysicsPlayers (
    ID UNIQUEIDENTIFIER NOT NULL,
    GameID UNIQUEIDENTIFIER NOT NULL,
    PlayerID UNIQUEIDENTIFIER NOT NULL,
    PlayerName NVARCHAR(1000) NULL,
    GuestPlayer BIT NOT NULL CONSTRAINT DF_PhysicsPlayers_GuestPlayer DEFAULT 0,
    PRIMARY KEY (ID)
);
CREATE TABLE PhysicsTurns (
    ID UNIQUEIDENTIFIER NOT NULL,
    GameID UNIQUEIDENTIFIER NOT NULL,
    PlayerID UNIQUEIDENTIFIER NOT NULL,
    RoundNumber INT NOT NULL,
    TurnValue INT NOT NULL,
    CreatedTimeStamp DATETIME NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE PhysicsGuestUsers (
    UserID UNIQUEIDENTIFIER NOT NULL,
    PlayerName NVARCHAR(1000) NOT NULL,
    Passcode NVARCHAR(100) NOT NULL,
    FirstLogin DATETIME NOT NULL,
    ClosedOut BIT NOT NULL,
);
