CREATE TABLE PhysicsGames (
    ID UNIQUEIDENTIFIER NOT NULL,
    CreatorID UNIQUEIDENTIFIER NOT NULL,
    JoinCode NVARCHAR(100) NOT NULL,
    GameStart DATETIME NOT NULL,
    NumPlayers INT NOT NULL,
    CurrentRound INT NOT NULL,
    GameEnd DATETIME NULL,
    WinningPlayerID UNIQUEIDENTIFIER NULL,
    WinningPlayerName NVARCHAR(1000) NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE PhysicsPlayers (
    ID UNIQUEIDENTIFIER NOT NULL,
    GameID UNIQUEIDENTIFIER NOT NULL,
    PlayerID UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE PhysicsTurns (
    ID UNIQUEIDENTIFIER NOT NULL,
    GameID UNIQUEIDENTIFIER NOT NULL,
    PlayerID UNIQUEIDENTIFIER NOT NULL,
    RoundNumber INT NOT NULL,
    TurnValue INT NOT NULL,
    CreatedTimeStamp DATETIME NOT NULL,
    PRIMARY KEY (ID)
);
